import naruto_shippuden from '../../assets/Toptenanimes/naruto_shippedun.jpeg'

export const Toptenanimelists = [
    {
        animenumber: "01",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        animenumber: "02",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "03",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "04",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "05",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "06",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "07",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "08",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "09",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },{
        animenumber: "10",
        animeimage: naruto_shippuden,
        animetitle: "Naruto: shippuden",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
]