import i_got_a_cheat_skill from '../../assets/allanimes/dragon_ball.jpg'

export const Allanimeslist = [
    {
        allanimeid: 1,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 2,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 3,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 4,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 5,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 6,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 7,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 8,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 9,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 10,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 11,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 12,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 13,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 14,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 15,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 16,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 17,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 18,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 19,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 20,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 21,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 22,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 23,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 24,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 25,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 26,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 27,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 28,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 29,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    },
    {
        allanimeid: 30,
        allanimeimage: i_got_a_cheat_skill,
        allanimename: "A Galaxy Next Door",
        allanimetiming: "23M",
        numberodsubepisode:"500",
        numberofdubepisode:"500",
        numberofepisode: "500",
    }
]